AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to map EngineVersion to Family for DBClusterParameterGroup

Mappings:
  EngineMap:
    '11':
      Family: 'aurora-postgresql11'
    '12':
      Family: 'aurora-postgresql12'
    '13':
      Family: 'aurora-postgresql13'
    '14':
      Family: 'aurora-postgresql14'
    '15':
      Family: 'aurora-postgresql15'
    '16':
      Family: 'aurora-postgresql16'
    'default':
      Family: 'aurora-postgresql'

Parameters:
  EngineVersion:
    Description: The Aurora PostgreSQL engine version
    Type: String
    Default: '13.3'

  MasterUsername:
    Description: The database admin account username
    Type: String
    Default: admin
    NoEcho: true

  DBClusterParameterGroupName:
    Description: The name of the DB cluster parameter group to associate with the DB cluster.
    Type: String

  VpcSecurityGroupId:
    Description: The VPC security group to associate with the DB cluster.
    Type: AWS::EC2::SecurityGroup::Id

  DBSubnetGroupName:
    Description: A DB subnet group to associate with the DB cluster.
    Type: AWS::RDS::DBSubnetGroup::Name

Conditions:
  IsAuroraPostgres11: !Equals [!Select [0, !Split [".", !Ref EngineVersion]], '11']
  IsAuroraPostgres12: !Equals [!Select [0, !Split [".", !Ref EngineVersion]], '12']
  IsAuroraPostgres13: !Equals [!Select [0, !Split [".", !Ref EngineVersion]], '13']
  IsAuroraPostgres14: !Equals [!Select [0, !Split [".", !Ref EngineVersion]], '14']
  IsAuroraPostgres15: !Equals [!Select [0, !Split [".", !Ref EngineVersion]], '15']
  IsAuroraPostgres16: !Equals [!Select [0, !Split [".", !Ref EngineVersion]], '16']
  IsValidMajorVersion: !Or
    - !Condition IsAuroraPostgres11
    - !Condition IsAuroraPostgres12
    - !Condition IsAuroraPostgres13
    - !Condition IsAuroraPostgres14
    - !Condition IsAuroraPostgres15
    - !Condition IsAuroraPostgres16

Resources:
  DBClusterParameterGroup:
    Type: AWS::RDS::DBClusterParameterGroup
    Properties:
      Description: Parameter group for Aurora PostgreSQL
      Family: !If
        - IsAuroraPostgres11
        - !FindInMap [EngineMap, '11', Family]
        - !If
          - IsAuroraPostgres12
          - !FindInMap [EngineMap, '12', Family]
          - !If
            - IsAuroraPostgres13
            - !FindInMap [EngineMap, '13', Family]
            - !If
              - IsAuroraPostgres14
              - !FindInMap [EngineMap, '14', Family]
              - !If
                - IsAuroraPostgres15
                - !FindInMap [EngineMap, '15', Family]
                - !If
                  - IsAuroraPostgres16
                  - !FindInMap [EngineMap, '16', Family]
                  - !FindInMap [EngineMap, 'default', Family]
      Parameters:
        max_connections: '100'

  AuroraPostgresDBCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      Engine: aurora-postgresql
      EngineVersion: !Ref EngineVersion
      MasterUsername: !Ref MasterUsername
      MasterUserPassword: !Ref MasterUserPassword
      DBClusterParameterGroupName: !Ref DBClusterParameterGroup
      VpcSecurityGroupIds:
        - !Ref VpcSecurityGroupId
      DBSubnetGroupName: !Ref DBSubnetGroupName
